### ISSUE TITLE
git clone不下来啊

### ISSUE THREAD

**Issue by tianpeidong** [spring2go/staffjoy#2]
git clone https://github.com/spring2go/staffjoy.git
正克隆到 'staffjoy'...
remote: Enumerating objects: 1665, done.
remote: Counting objects: 100% (1665/1665), done.
remote: Compressing objects: 100% (1048/1048), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
fatal: The remote end hung up unexpectedly
fatal: 过早的文件结束符（EOF）
fatal: index-pack 失败

**Comment by 1194117884** [comment]
可以下载的，应该是本机git的问题
请自行搜索下解决方法，很多的！

**Comment by jskillnet** [comment]
全部clone下载有50m左右，国内网络有时下载github比较慢，建议凌晨网络空闲时候下。也可以直接下载zip文件，大致17m左右。
