### ISSUE TITLE
web app 模块 HelperService buildUrl 方法应该删除  static 标识

### ISSUE THREAD

**Issue by medoer** [spring2go/staffjoy#7]

**Comment by jskillnet** [comment]
有什么问题？影响程序逻辑吗？

**Comment by forjyoung** [comment]
> 有什么问题？影响程序逻辑吗？

没有影响， HelperService 实例化成了 spring bean ，在 web-app 模块里 buildUrl 方法既有 static 调用也有注入后的调用，统一一下比较好。
